import type { Metadata } from "next";
import Navbar from "./components/navbar/navbar";
import { Inter } from "next/font/google";
import "./globals.css";
import AuthProvider from "./components/auth-provider/auth-provider";
import CheckAuth from "./chechAuth";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" data-theme="business">
      <body className={inter.className}>
        <AuthProvider>
          <CheckAuth>
            <Navbar pathname={"/"} />
            {children}
          </CheckAuth>
        </AuthProvider>
      </body>
    </html>
  );
}
