import type { Metadata } from "next";
import Navbar from "./components/navbar/navbar";
import { Inter } from "next/font/google";
import "./globals.css";
import AuthProvider from "./components/auth-provider/auth-provider";
import CheckAuth from "./chechAuth";

// Это шрифт
const inter = Inter({ subsets: ["latin"] });

// Метаданные
export const metadata: Metadata = {
  title: "Reception GYM",
  description: "Generated by create next app",
};

// Компонент рута
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // Отдаем базовый html
  return (
    <html lang="en" data-theme="business">
      <body className={inter.className}>
        {/* Обертка для получения данных авторизации */}
        <AuthProvider>
          {/* Проверка авторизации */}
          <CheckAuth>
            {/* Навигационная панель */}
            <Navbar pathname={"/"} />
            {/* страницы */}
            {children}
          </CheckAuth>
        </AuthProvider>
      </body>
    </html>
  );
}
